M48
; DRILL file {KiCad 7.0.9-7.0.9~ubuntu20.04.1} date Fri 02 Feb 2024 11:04:40 GMT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-02-02T11:04:40+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9-7.0.9~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1693
%
G90
G05
T1
X6.15Y-2.8
X6.15Y-5.15
X9.6Y-2.8
X9.6Y-5.15
T0
M30
